<a href="https://colab.research.google.com/github/Ferarenas14/Ferarenas14/blob/main/Factorizaci%C3%B3n_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Factorización LU

In [2]:
import numpy as np

def factorizacion_LU(A):
    n = A.shape[0]  # Tamaño de la matriz A
    L = np.zeros((n, n))  # Inicialización de L
    U = np.zeros((n, n))  # Inicialización de U

    # Paso 1: Inicializar L11 = 1 y U11 = a11
    if A[0, 0] == 0:
        print('Factorización imposible')
        return None, None

    L[0, 0] = 1
    U[0, 0] = A[0, 0]

    # Paso 2: Calcular la primera fila de U y la primera columna de L
    for j in range(1, n):
        U[0, j] = A[0, j] / L[0, 0]
        L[j, 0] = A[j, 0] / U[0, 0]

    # Paso 3 y 4: Iterar para calcular las matrices L y U
    for i in range(1, n):
        # Paso 4: Calcular L[i,i] y U[i,i]
        suma_LU = np.dot(L[i, :i], U[:i, i])
        if A[i, i] - suma_LU == 0:
            print('Factorización imposible')
            return None, None

        L[i, i] = 1
        U[i, i] = A[i, i] - suma_LU

        # Paso 5: Calcular la fila i de U y la columna i de L
        for j in range(i + 1, n):
            suma_LU = np.dot(L[i, :i], U[:i, j])
            U[i, j] = (A[i, j] - suma_LU) / L[i, i]

        for j in range(i + 1, n):
            suma_LU = np.dot(L[j, :i], U[:i, i])
            L[j, i] = (A[j, i] - suma_LU) / U[i, i]

    # Paso 6: Calcular el último elemento Lnn * Unn
    suma_LU = np.dot(L[n-1, :n-1], U[:n-1, n-1])
    if A[n-1, n-1] - suma_LU == 0:
        print('Factorización imposible')
        return None, None

    L[n-1, n-1] = 1
    U[n-1, n-1] = A[n-1, n-1] - suma_LU

    # Paso 7: Mostrar las matrices L y U
    print("Matriz L:")
    print(L)
    print("Matriz U:")
    print(U)

    return L, U


# Ejemplo
A = np.array([[1, 1, 0, 3],
              [2, 1, -1, 1],
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype=float)

L, U = factorizacion_LU(A)

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]
Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
